### ISSUE TITLE
Alacritty字体之间错位

### ISSUE THREAD

**Issue by Feiyuyu0503** [EvanMeek/Vanilla#1]
您好，看到您blog上的图片似乎也有这样的问题，请问您有解决方案吗

**Comment by EvanMeek** [comment]
可以给我下具体是哪篇文章嘛，解决方案是你需要更换字体。

**Comment by Feiyuyu0503** [comment]
具体是这篇文章 https://evanmeek.github.io/2019/07/03/%E6%9C%80%E5%BF%AB-GPU%E5%8A%A0%E9%80%9F-Alacritty%E7%BB%88%E7%AB%AF/
